using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Namespace2;
namespace Namespace2.Tests
{
    [TestFixture]
    public class Class1Tests
    {
        [Test]
        public void KekTest()
        {
            Assert.Fail("autogenerated");
        }
    }

    [TestFixture]
    public class Class2Tests
    {
        [Test]
        public void LolTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}