using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using MyNamespace1;
namespace MyNamespace1.Tests
{
    [TestFixture]
    public class SimpleClassTests
    {
        [Test]
        public void ATest()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void BTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}