using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Namespace3;
using Namespace4;
namespace Namespace3.Tests
{
    [TestFixture]
    public class Class1Tests
    {
        [Test]
        public void aTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}
namespace Namespace4.Tests
{
    [TestFixture]
    public class Class2Tests
    {
        [Test]
        public void aTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}