using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using MyNamespace1;

namespace MyNamespace1.NUnitTests
{
    [TestFixture]
    public class SimpleClassTest
    {
        private SimpleClass _simpleClass
        {
            get;
            set;
        }

        [Test]
        public void ATest()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void BTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}